### PR TITLE
bugfix: SubQuery params binding resolved

### PR DESCRIPTION
**Pull request by SohrabZ**

### CODE REVIEW

**Comment by SohrabZ** [comment]
@hamed-aloware Use PHP CS fixer to cleanup the code styling: 
```
composer require --dev aloware/shift-php-cs:dev-master
```

More info: https://github.com/aloware/shift-php-cs

**Comment by SohrabZ** [comment]
@hamed-aloware Also add compatibility to the `README.md`

**Comment by kamrava** [comment]
> @hamed-aloware Use PHP CS fixer to cleanup the code styling:

Done

> @hamed-aloware Also add compatibility to the `README.md`

Done

**Comment by hamed-aloware** [comment]
> @hamed-aloware Use PHP CS fixer to cleanup the code styling:

Done

> @hamed-aloware Also add compatibility to the `README.md`

Done

**Comment by hamed-aloware** [comment]
> @hamed-aloware Use PHP CS fixer to cleanup the code styling:

Done

> @hamed-aloware Also add compatibility to the `README.md`

Done

**Pull request merged**
